### ISSUE TITLE
[Request] Create an example on how to upgrade this project

### ISSUE THREAD

**Issue by itsho** [reportportal/example-net-specflow-nunit2-log4net#2]
is it possible to create a branch demonstrating how to upgrade this project to latest NuGet versions? (SpecFlow 3+ & etc.)?
I think it has a great value for everyone - myself included.

I've tried to do it myself but had too many errors and API changes which I was unable to resolve.

thanks in advance.

**Comment by nvborisenko** [comment]
https://github.com/reportportal/example-net-specflow - please find example here, this repo is actual.

**Comment by itsho** [comment]
I'm aware to the new example. the point it that the upgrade process is complicated. 

### Things which I managed to figure out:
* new namespaces (`ReportPortal.Client.Requests` -> `ReportPortal.Client.Abstractions.Requests` etc.)
* removing the Custom Tool Namespace
* `Bridge.Service.AddLogItem(..)` -> `Context.Current.Log.Info(..)` etc.
* `StartLaunchRequest.Tags` -> `StartLaunchRequest.Attributes`
* in `Service` ctor, `WebProxy` -> `ReportPortal.Client.IHttpClientFactory`
* `ScenarioContext.Current` -> Context injection via ctor

### Things I haven't figured out:
* in `ReportPortalAddin` static ctor - where should I set the new Service? the `Bridge` object no longer exist!?
* in `BeforeTestRun`/`AfterTestRun` - where do I get/set `Bridge.Context.LaunchId`?
* in `BeforeTestRun`/`AfterTestRun` - where do I get the `Bridge.Service` object from?

Thanks in advance

**Comment by nvborisenko** [comment]
> where should I set the new Service? the Bridge object no longer exist!?

No static `Bridge` anymore. To set new `Service` object subscribe on `Initializing` event and then in handler `e.Service = your_object`.

> in BeforeTestRun/AfterTestRun - where do I get/set Bridge.Context.LaunchId?

Since no `Bridge` object, most of objects shared through handler events. For this particular case: `e.LaunchReporter.Info.Uuid`. Don't forget that reporting is async. To wait until launch presents on server use `e.LaunchReporter.Sync()`.

> in BeforeTestRun/AfterTestRun - where do I get the Bridge.Service object from?

`e.Service`

**Comment by itsho** [comment]
Thank you.
